### ISSUE TITLE
Replace WebServer with a ServiceWorker

### ISSUE THREAD

**Issue by sirdarckcat** [google/tamperchrome#1]
This will allow us to modify POST data on XHR requests among other things (once ForeignFetch is implemented in Chrome).

**Comment by bobbi216** [comment]
I can not get 2 step verification nor do any of my back up codes work.

**Comment by zonestc** [comment]
Sxs madina  ksa

**Comment by sirdarckcat** [comment]
another way to fix this would be to not wait for foreignFetch, and intercept requests reusing the current infrastructure, but capturing the requests onfetch for the controlling service worker.

that said, this isnt possible because at least in chrome service workers cant intercept synchronous XHR requests
https://bugs.chromium.org/p/chromium/issues/detail?id=602051

**Comment by sirdarckcat** [comment]
unfortunately, foreignFetch wont be implemented as specd.. this means the service worker approach wont work for tamper chrome.

it also doesn't seem like extensions will be given access to sockets, which means TamperChrome's server might not work at all.

**Comment by sirdarckcat** [comment]
https://github.com/w3c/ServiceWorker/issues/1188

**Comment by sirdarckcat** [comment]
Firefox seems to support this:
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/onBeforeRequest

**Comment by sirdarckcat** [comment]
since foreignFetch is dead, and there doesn't seem to be any chance of it coming back, closing this
