### ISSUE TITLE
Response Header editing issues

### ISSUE THREAD

**Issue by sirdarckcat** [google/tamperchrome#122]
Response headers dont get properly modified. Only Location seems to be working properly when used with 30X.

There is at least one unit test that shows it should work https://source.chromium.org/chromium/chromium/src/+/master:third_party/blink/web_tests/http/tests/inspector-protocol/fetch/fetch-binary-headers.js;l=50?q=binaryResponseHeaders&ss=chromium

```javascript
fetch('/subresource').then(r =>
          [r.headers.get('X-Test-Header'), r.headers.get('X-Another-Header')])
```

with
```javascript
  helper.onceRequest().fulfill({
    responseCode: 200,
    binaryResponseHeaders: btoa('X-Test-Header: hétérogénéité\0X-Another-Header: value'),
    body: ""
  });
```

however, since this works for location, it's possible there's something else broken here.

**Comment by sirdarckcat** [comment]
this needs a short reproducer that just does the exact same thing as the test, but from a chrome extension.

**Comment by sirdarckcat** [comment]
it's possible that responding with fulfillRequest too late (after headers are received) might not be possible. this means that to make this work, we would need to always redirect the user, to a same-origin URL, and intercept that request and return a response instead.

**Comment by sirdarckcat** [comment]
just tried to fulfillRequest at request time, and it didn't fix it

**Comment by sirdarckcat** [comment]
https://github.com/subwaymatch/cdp-modify-response-example implies this works

**Comment by sirdarckcat** [comment]
One theory, is that response header modifications only really apply to some logic. Such as that implemented here https://source.chromium.org/chromium/chromium/src/+/master:content/browser/devtools/devtools_url_loader_interceptor.cc;l=1009;drc=7228a109083df80bef55725fc4bc7b92896d355f

That would explain why some things work, but not others.

**Comment by sirdarckcat** [comment]
If it's ultimately not possible to fix this, it's still possible to hack around this by mixing debugger API with webRequestBlocking

**Comment by sirdarckcat** [comment]
this works https://bugs.chromium.org/p/chromium/issues/detail?id=1162738

i have no idea why it didnt work for me before

**Comment by geneerik** [comment]
Hi @sirdarckcat .  I am having this very issue.  I am trying to update the cache-control header on a response im working on and it doesnt want to update. I am on version 2.0.9 on Chrome Version 108.0.5359.94 (Official Build) (64-bit) on a Debian-base Linux distro. I cannot, in fact, seem to do ANYTHING to the headers, though i can change the response body.  Should I open a new ticket? The effect seems to be the same as described at the first message of the issue.
