### ISSUE TITLE
Modify response content

### ISSUE THREAD

**Issue by stevobm** [google/tamperchrome#14]
I think it's useful to replace the body of response when debugging a webapp, does tamper chrome support the function?

**Comment by sirdarckcat** [comment]
could you explain your use case a bit better?

it kindof allows you to do that, but depends on what you mean exactly =)

what type of task are you trying to do?

**Comment by stevobm** [comment]
I want to simulate an interface with tamperchrome so that I can send ajax request in chrome and get the response even if it hasn't been implemented by the backend yet.

**Comment by sirdarckcat** [comment]
Ok, thanks a lot.

The page you are testing is http or https?

This use case actually was implemented before but I removed it. I could bring it back in a hacky/imperfect way relatively quickly for some sites (http only), or you could subscribe to issue #1 for the more elegant solution :-)

**Comment by stevobm** [comment]
Ok, that's exactly what I want. I wanna use it and also prefer it a perfect way. Waiting for your good news :-)

**Comment by sirdarckcat** [comment]
Sweet!!

**Comment by bag-man** [comment]
@sirdarckcat Is this dead in the water then? Looks like the other issue you linked is not possible. Have you found an alternative?

**Comment by sirdarckcat** [comment]
I'm currently working on https://github.com/google/tamperchrome/issues/31 which among other things, makes this possible.
