### ISSUE TITLE
Feature: Cookies

### ISSUE THREAD

**Issue by jdcaballerov** [google/tamperchrome#2]
Is there any way to see the cookies being sent on Mac?

**Comment by eliyastein** [comment]
@jdcaballerov - if you click request or response headers the cookie field is clearly shown for each request intercepted.

**Comment by sirdarckcat** [comment]
@jdcaballerov did the answer from @eliyastein answer your question?

if not please let me know

**Comment by sirdarckcat** [comment]
please @ me if this doesn't work for your use case

thank you
