### ISSUE TITLE
Tamper Chrome won't start

### ISSUE THREAD

**Issue by sirdarckcat** [google/tamperchrome#20]
_From @Fandekasp on May 19, 2017 8:29_

After installing both the extension and the app, I'm still unable to use Tamper Chrome, the debugger console tab showing "Requires a second component" error:
![2017-05-19_17-26-31](https://cloud.githubusercontent.com/assets/260983/26239567/883864c0-3cb8-11e7-8cea-1679d60c9340.png)
Tried restarting the browser twice, didn't help.

Using Google Chrome Version 58.0.3029.110 (64-bit) from Arch Linux.

_Copied from original issue: sirdarckcat/sirdarckcat.github.io#2_

**Comment by sirdarckcat** [comment]
Oh, wow, thanks for letting us know!

This is really strange, out of curiosity, which operating system do you use?

**Comment by sirdarckcat** [comment]
_From @Fandekasp on May 19, 2017 8:41_

```
$ uname -a                                                                                         [17:39:23]
Linux xps_9360 4.10.13-1-ARCH #1 SMP PREEMPT Thu Apr 27 12:15:09 CEST 2017 x86_64 GNU/Linux
$ cat /etc/os-release                                                                              [17:39:26]
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
ID_LIKE=archlinux
ANSI_COLOR="0;36"
HOME_URL="https://www.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"

$ pacman -Qs chrome                                                                                [17:39:29]
local/google-chrome 58.0.3029.110-1
    An attempt at creating a safer, faster, and more stable browser (Stable Channel)
```

Fyi I was using tamper chrome last year on arch linux.
Thank you for the fast support !

**Comment by sirdarckcat** [comment]
do you have iptables/pf setup?

The way TC works is by opening a local port, so if you have a firewall rule preventing connections from localhost to localhost, this could happen.

**Comment by sirdarckcat** [comment]
_From @Fandekasp on May 19, 2017 8:57_

No such rule in my iptables. Also, when opening the application from the chrome store page (useless because I cannot access the settings that are in the extension), I cannot see any related port being open. Or would that be scriptview ?

```
$ Starting Nmap 7.40 ( https://nmap.org ) at 2017-05-19 17:54 JST
Nmap scan report for localhost (127.0.0.1)
Host is up (0.00013s latency).
Other addresses for localhost (not scanned): ::1
rDNS record for 127.0.0.1: localhost.localdomain
Not shown: 997 closed ports
PORT     STATE SERVICE
443/tcp  open  https
3306/tcp open  mysql
7741/tcp open  scriptview
```

**Comment by sirdarckcat** [comment]
no, the port is 34013. can you click on the link `background page (Inactive)` under Tamper Chrome (application) and send over the contents of the console.log?

Thanks

**Comment by Fandekasp** [comment]
@sirdarckcat hmm, this morning the issue seems to have been fixed. the port 34013 is opened (service unknown), and the chrome debug Tamper tab shows the settings as expected. 

What I did over the weekend: restart the computer, upgrade packages. Probably one of the 2 solved it.

**Comment by sirdarckcat** [comment]
Awesome! It's strange why this happened anyway. Maybe we should consider sending a message to the app through chrome.runtime to check it the app is installed but binding to the port is what failed.

**Comment by kekenec** [comment]
Same problem here, i'm using Windows 10 (disabled firewall), app v1.3.1, extension v1.3.2. Usually solved by restarting browser. Could it be version conflict? I tried to reinstall both from chrome store, but still got different versions.

**Comment by sirdarckcat** [comment]
Reopening since I think it's something else.

One potential problem might be when two apps installed in two different profiles interact with each other, but that shouldn't cause breaking behavior.

If someone can reproduce this consistently please let me know and reopen this bug.

**Comment by sirdarckcat** [comment]
sorry, I mean please comment on this bug. the bug is already reopened..

**Comment by Martin288** [comment]
Got same issue now, is there any solution now?

I am using Mac OS 10.11.6

**Comment by sirdarckcat** [comment]
@Martin288 does it show you the "Please install the app error"?

what version of the app/extension do you have?

**Comment by Martin288** [comment]
@sirdarckcat yes, it does. I installed the newest versions for both app and extension from chrome app store, this error is annoying. Maybe I need to check if any error message printed in console by the background page of the extension?

**Comment by Martin288** [comment]
@sirdarckcat Feel so strange that it works now! I just uninstall both app and extension, and after that I install the extension firstly, and then click the app link in the extension page, after all installations are finished, it is back to normal now!
FYI, I installed them in reverse order last week and them doesn't work.

**Comment by sirdarckcat** [comment]
:) awesome
