### ISSUE TITLE
Failed to launch Tamper

### ISSUE THREAD

**Issue by dwisiswant0** [google/tamperchrome#205]
Hi, an error occurs when trying to launch Tamper:

```
Failed to attach to https://chrome.google.com/webstore/detail/tamper-dev/mdemppnhjflbejfbnlddahjbpdbeejnn/related - probably because of enterprise policies.
```

Environments:
```
Linux x86_64
Chrome Version 89.0.4389.90 (Official Build) (64-bit)
```

**Comment by sirdarckcat** [comment]
Yes, chrome.google.com is not allowed to have chrome extensions :-(

**Comment by dwisiswant0** [comment]
OMEGALOL, my bad. But it same when try on another sites.

**Comment by sirdarckcat** [comment]
Which sites? Maybe it's due to another Chrome Extension. See #199 for example.

**Comment by dwisiswant0** [comment]
> Which sites? Maybe it's due to another Chrome Extension. See #199 for example.

Like `youtube.com`. I've read that related issue, but I can't identify which extension has an enterprise policy.

### Workaround

Browse to `chrome://policy`, see which extensions have enterprise policies, uninstall them _(**GNOME Shell integration** in my case)_, finally restarting Chrome. It should be working!
