### ISSUE TITLE
Unable to Intercept Youtube

### ISSUE THREAD

**Issue by repository** [google/tamperchrome#208]
Hello.

I am unable to use Tamper on Youtube. It's unable to attach every time..
![image](https://user-images.githubusercontent.com/41586666/113738281-9ea72a80-96b3-11eb-8f55-bab00af0384f.png)
Incognito window w/ only Tamper active

**Comment by sirdarckcat** [comment]
can you check if you have the YouTube app installed in chrome://apps/?

**Comment by repository** [comment]
I did, but I've removed it since and it still doesn't work

Nevermind, I could've sworn I removed it. Maybe there were two, I don't know. Anyways, it is working now.

**Comment by sirdarckcat** [comment]
thanks!!
