### ISSUE TITLE
Tamper chrome application window can't be reopened once closed, subsequent requests hang browser?

### ISSUE THREAD

**Issue by jikamens** [google/tamperchrome#25]
On Ubuntu 17.04:

1. Visit a site.
2. Ctrl-shift-C.
3. Tamper tab.
4. Check "Block / Reroute Requests".
5. Click a link.
7. Keep clicking "Allow" in the Tamper Chrome application window that pops up until the page is finished loading.
8. Close the Tamper Chrome application window.
9. Click another link.

At this point the browser says it's waiting for the Tamper Chrome application and just hangs there. The Tamper Chrome application window doesn't pop open again, and I can't find any way to reopen it. The only recourse at this point appears to be to completely exit from Chrome, including background Chrome processes, and restart it.

**Comment by sirdarckcat** [comment]
would you mind please checking if the current version still has this behavior?

just download the repository no building required.

**Comment by jikamens** [comment]
I tried installing the extension both from the most recent zip release and from the tamperchrome/extension directory in the github tree. Both still have this issue.

**Comment by sirdarckcat** [comment]
mmm which website are you testing on?

I cant reproduce :(

**Comment by jikamens** [comment]
Every web site I've tried. Even something as simple as neverssl.com. Load neverssl.com, ctrl-shift-c, tamper pane, check block / reroute requests, refresh page, click allow in tamper chrome window until the page loads, close tamper chrome window, refresh page again. Browser hangs talking to tamper chrome extension until I quit and restart chrome.

**Comment by sirdarckcat** [comment]
I must be doing something wrong, or maybe there's something special about your installation or chrome version that is causing troubles.

could you please check if doing what I do in the video has the same behavior for you?

thank you!!

https://youtu.be/Vvll04Sc7yU

**Comment by jikamens** [comment]
Here's the video demonstrating my problem:

https://www.youtube.com/watch?v=uyVCmw8CyEA

Is it possible that I need a newer version of the app? How do I install a newer version than what's in the chrome web store? Actually, I honestly don't know where I got the app version that I currently have installed; I just followed whatever instructions I was given to install it when I tried to use the extension the first time. I can't actually find the app in the chrome web store, so I don't know where it came from.

**Comment by jikamens** [comment]
Aha! That did it. Installing the newest version of the app from the source tree along with the newest version of the extension solved this problem.

It would probably be a good idea to ship the newest code for both the app and the extension. ;-)

**Comment by sirdarckcat** [comment]
Oh that's awesome :-).

Thanks for your help!
