### ISSUE TITLE
Request: getMessage tampering

### ISSUE THREAD

**Issue by JemiloII** [google/tamperchrome#27]
So it's cool that I can modify a post response from the server, but what about a get?

**Comment by sirdarckcat** [comment]
Hi

What do you mean?

**Comment by JemiloII** [comment]
sorry for the late reply. I wanted to have a get request that returns data from my server to be modified before it was returned.

**Comment by sirdarckcat** [comment]
can you provide some more details? what type of data was it?

**Comment by JemiloII** [comment]
it returns as json data, I work with all json apis with get, post, put, and delete.

**Comment by sirdarckcat** [comment]
and you want to see how the application would behave if the data was different, right?

this is not immediately easy to implement, but it's also not impossible.. needs a bit of work.

how often do you need to do this? is this a semi-regular thing or something you just had to do once?

**Comment by dominiczen** [comment]
I agree with you!

On Jul 11, 2017 2:47 PM, "Brian M. Jemilo II" <notifications@github.com>
wrote:

So it's cool that I can modify a post response from the server, but what
about a get?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/google/tamperchrome/issues/27>, or mute the thread

**Comment by JemiloII** [comment]
It's something I'd use all the time. My entire api uses json for get, post, put, patch, and delete. Currently I use either httpMockBackend or Nock to mock my responses. but its a lot to setup just to do simple data checks.

**Comment by sirdarckcat** [comment]
ok, thanks.

I'll try to get to it when I have a bit of time. Technically, the way to implement this would be to send the content back to the page, store the JSON in the filesystem API and then redirect the page to there. I think this works, but I will need to confirm.

**Comment by sirdarckcat** [comment]
I think that the bang-for-buck is better spent implementing https://github.com/google/tamperchrome/issues/31 which will make this possible as well
