### ISSUE TITLE
Modify post body

### ISSUE THREAD

**Issue by fixwa** [google/tamperchrome#28]
Same as issue #7 
When i block a request, is there a way for me to modify the post body and then forward it to the intended server.

The textarea won't let you edit the post body

**Comment by sirdarckcat** [comment]
Does Replay do what you need? If not , could you describe the task you are working on?

**Comment by fixwa** [comment]
Not really; by using Replay, it will just send that request alone. However, by using the Block/Reroute feature, it will: 

* Send some requests I don't want to modify but are necessary to setup the context of the issue.
* Halt the request that I am interested in, and allow me to modify the URL and the HEADERS, but not the BODY.
* Allow to continue and send other requests that also are necessary for the context.

**Comment by Sphiinx** [comment]
@fixwa Did you ever figure out a solution to that?

**Comment by fixwa** [comment]
@Sphiinx cc/ @sirdarckcat no, unfortunately. 
What I found is that there's an [open issue](https://bugs.chromium.org/p/chromium/issues/detail?id=104058) for chromium and it is not expected to be fixed any soon.

**Comment by Sphiinx** [comment]
@fixwa Thanks for the info!

**Comment by fixwa** [comment]
np. I'm closing this for now

**Comment by phillip055** [comment]
Any solutions found?

**Comment by sirdarckcat** [comment]
This isn't currently possible, unfortunately
