### ISSUE TITLE
Automatically set a Public-Key-Pins-Report-Only header with custom report-uri

### ISSUE THREAD

**Issue by kerberosmansour** [google/tamperchrome#29]
As a security engineer I want an extension which automatically adds a Public-Key-Pins-Report-Only header to all sites and for me to provide it a custom report-uri so that I could get alerts when I am being MITM'd without being locked out to sites I care about (hence report only mode).

Can Tamperchrome help?

**Comment by sh1ftchg** [comment]
As a Security Architect I can tell you no, "these are not the droids you are looking for, move along."

But as a peer in a small community I feel obligated to at least help: refer to the (chrome extension development)[https://developer.chrome.com/extensions/getstarted] guide. Specifically, chrome.webRequest.onBeforeSendHeaders(callback), if memory serves.

**Comment by sirdarckcat** [comment]
Probably better to use an extension that persistently changes headers. Tamper Chrome currently is only targeted for manual pentesting and debugging.

**Comment by kerberosmansour** [comment]
Any one you recommend?
