### ISSUE TITLE
Unreadable text with dark theme

### ISSUE THREAD

**Issue by brian-gates** [google/tamperchrome#3]
With the dark theme enabled, this tool is unreadable.

**Comment by eliyastein** [comment]
@brian-gates - I also discovered this. I just submitted a PR to address this by changing the label color to blue. If you want a work around in case the PR doesn't get accepted, then you can launch devtools within devtools and just change the color of the label to blue (or something with a bit more contrast).

**Comment by sirdarckcat** [comment]
thanks for the PR, sent you some comments.

sorry for the delay

**Comment by sirdarckcat** [comment]
This is fixed https://github.com/google/tamperchrome/pull/5 by @eliyastein

**Comment by sirdarckcat** [comment]
still not fixed, new change:
https://github.com/google/tamperchrome/commit/aec9a405533903f3500eded7d1c4dc65b9093bf4

**Comment by judysshit6** [comment]
Thank u is their any way i can keep this person from spying on everything i
do on my phone

**Comment by sirdarckcat** [comment]
jaja what?

**Comment by judysshit6** [comment]
Get off my lage

On Jun 3, 2017 2:22 PM, wrote:

https://github.com/pugjs/brjade/blob/master/package.json

**Comment by judysshit6** [comment]
Check out "IBA Opt-out (by Google)":
https://chrome.google.com/webstore/detail/iba-opt-out-by-google/gbiekjoijknlhijdjbaadobpkdhmoebb?utm_source=gmail
