### ISSUE TITLE
Let us modify the body of intercepted requests

### ISSUE THREAD

**Issue by Fredyy90** [google/tamperchrome#32]
This Chrome extensions is great and should be a core function of Google Chrome, but one key feature is missing.

Currently you can intercept all kinds of requests and modify their headers, before they are send out, but there ist no option to see and modify the body of these requests.

Please add this feature as it would be very helpfull to test all kinds weird edge cases, without using external software like charlesproxy etc.

**Comment by paresh-rbc** [comment]
I see option available, but is it working now? When I try to modify my body, it doesn't send modified request to the backend.. !
<img width="678" alt="2018-04-20_1115" src="https://user-images.githubusercontent.com/35930286/39059406-5f7167a8-448c-11e8-9728-806010e73008.png">
Is that what I should expect right now as this is still an experimental feature? Thanks!

**Comment by VarunAgw** [comment]
From my understanding, you need to run a proxy server to achieve this functionality. Chrome doesn't have such functionality and they don't want to either for many reasons

**Comment by sirdarckcat** [comment]
I'm currently experimenting with a new API https://github.com/google/tamperchrome/issues/31 that would allow to simplify the UI https://github.com/google/tamperchrome/issues/18 as well as making this and other things possible
