### ISSUE TITLE
feature: Filtering

### ISSUE THREAD

**Issue by qm3ster** [google/tamperchrome#34]
Allow automatically ignoring or automatically blocking requests based on:
  - at least the url and headers, like chrome network tab,
  - but ideally also on body content.

Otherwise many pages bombard you with requests you don't care about, sometimes faster than you can get rid of them.

**Comment by sirdarckcat** [comment]
have you tried the "Ignore [...]" tools? if they weren't useful, any idea why?

**Comment by qm3ster** [comment]
They're too coarse.
I only didn't ignore the XHR, and even among those I needed to only catch one URL to be usable.

Also maybe add a "check all boxes" button to the ignores.

**Comment by sirdarckcat** [comment]
I like "check all boxes" idea.

adding UI to filter a specific path sounds reasonable, not sure how much work that is

**Comment by sirdarckcat** [comment]
From #35 
```
I selected every ignore option except for "ignore subframe" and enabled "Block/Reroute Requests" but fonts and media requests are still captured.

I would also like to recommend three features:

1. Ignore All (checks all ignore options so you can only deselect the ones you want; makes things easier and faster)
2. Restrict to URL/Domain (only capture requests to a specified domain/URL; makes the app cleaner, faster, and easier and allows you to better isolate the request you're looking for; I'm aware of the filter in the app but it still captures requests from other URLs)
3. Ignore Media (video & audio)

Google Chrome is up to date: Version 67.0.3396.79 (Official Build) (64-bit)
Windows 10 Home: Version 1803
```

**Comment by sirdarckcat** [comment]
I think that the main usecase for this is either:

1. select a single "type"
1. filter by url
1. no filtering

so, I think the easiest way to use this would just be, in the new UI (#18), to allow the user to filter by URL and/or by type, and by default have no filtering.

will track this on #18 the new API in #40 has basic support for URL filtering, will add type filtering too
