### ISSUE TITLE
Font Filter

### ISSUE THREAD

**Issue by GrimReaper420** [google/tamperchrome#35]
I selected every ignore option except for "ignore subframe" and enabled "Block/Reroute Requests" but fonts and media requests are still captured.

I would also like to recommend three features:

1. Ignore All (checks all ignore options so you can only deselect the ones you want; makes things easier and faster)
2. Restrict to URL/Domain (only capture requests to a specified domain/URL; makes the app cleaner, faster, and easier and allows you to better isolate the request you're looking for; I'm aware of the filter in the app but it still captures requests from other URLs)
3. Ignore Media (video & audio)

Google Chrome is up to date: Version 67.0.3396.79 (Official Build) (64-bit)
Windows 10 Home: Version 1803

**Comment by sirdarckcat** [comment]
tracking this in #34
