### ISSUE TITLE
Similar TamperHeaders extension developed by me for developers

### ISSUE THREAD

**Issue by VarunAgw** [google/tamperchrome#36]
Hello folks! 

Nice extension. Just want to drop by and say hi. I also developed a similar extension (mainly for myself) 2 years ago.

Instead of interface, it's more scripting based. It just make it very simple to play with the API's and develop your rules.

It's not on chrome store (for a reason). Just download it, and play with it. If you have any question, feel free to write me (Varun@VarunAgw.com) :)

https://github.com/VarunAgw/TamperHeaders

**Comment by sirdarckcat** [comment]
thanks :)
