### ISSUE TITLE
Forms headers of requests

### ISSUE THREAD

**Issue by oleedd** [google/tamperchrome#38]
It doesn't display forms headers of requests if a request is made from form element. This is very sad.

**Comment by sirdarckcat** [comment]
can you explain what you mean?

**Comment by oleedd** [comment]
If there is \<form\> element - \<input\> elements (name and value attributes) will create headers. And a request in such case is made by submitting of this form. It is very common and exists almost on every site. But forms headers are generally not displayed in this extension for some reason.

**Comment by oleedd** [comment]
If there is <form> element - <input> elements (name and value attributes) will create headers. And a request in such case is made by submitting this form. It is very common and exists almost on every site. But forms headers are generally not displayed in this extension for some reason.

**Comment by oleedd** [comment]
If there is \<form\> element - \<input\> elements (name and value attributes) will create headers. And a request in such case is made by submitting this form. It is very common and exists almost on every site. But forms headers are generally not displayed in this extension for some reason.

**Comment by sirdarckcat** [comment]
by headers, do you mean the request body?

**Comment by oleedd** [comment]
I just mean headers created by form. Idk what is request body.
You can see this popular extension in such area. It only allows to display headers but supports forms headers too.
https://chrome.google.com/webstore/detail/http-header-spy/agnoocojkneiphkobpcfoaenhpjnmifb

**Comment by sirdarckcat** [comment]
ok, yea thats the request body. chrome's api to modify the request body is #31 so that's the right bug to track to get this

**Comment by oleedd** [comment]
Will it be supported soon?
