### ISSUE TITLE
How to modify the Post request body? 

### ISSUE THREAD

**Issue by sajadi** [google/tamperchrome#39]
I want to change parameters of the Post request on the fly but it is locked. I'm going to change the Request body before submitting via Tamper Chrome.
It is a basic functionality that Tamper should support.

![untitled](https://user-images.githubusercontent.com/5206953/50909578-661b3680-1441-11e9-999e-bd39ff85e864.png)

**Comment by sirdarckcat** [comment]
unfortunately this only works if you select "replay" because of limitations in the api
