### ISSUE TITLE
Copying request details

### ISSUE THREAD

**Issue by homakov** [google/tamperchrome#4]
It would be very useful to have one button to copy all request details (URL+body+all headers and cookies) to replay it in console, modify or run it from your server. Recommended format: curl or HAR.

**Comment by sirdarckcat** [comment]
hi

if there is POST data included, what would you expect to happen? should the request include the POST data or not?

this would probably be the easiest to implement in Response Headers.

also, this would still forward the request after the request is done, IIRC from twitter you also wanted to cancel the request. would you like to be able to cancel the request at the end? (it's still possible, although different)

**Comment by homakov** [comment]
Yes it should include all data. I want request cancelled completely because I already have the details of request i want to make and can do it myself.

**Comment by sirdarckcat** [comment]
ok, thanks. cancelling the request then is a bit more complicated, but doable.

**Comment by homakov** [comment]
not urgent for me anymore: figured out how to trivially do it with cancel: true and retrieve entire request data in my own extension.

**Comment by sirdarckcat** [comment]
cool! were you able to cancel the request after the request headers are committed?

According to the docs [onSendHeaders](https://developer.chrome.com/extensions/webRequest) is not allowed to cancel the request, which means that you probably need to get a hold of the request id and then fetch the request data with devtools.network?

Or how did you do it?

**Comment by homakov** [comment]
I get the body in onBeforeRequest and save it for its requestId, then inside onBeforeSendHeaders I can see headers and cancel it. I don't use onSendHeaders as I am not interested in how headers could be modified by some extensions.

**Comment by sirdarckcat** [comment]
Oh, OK. OnBeforeRequest doesn't have the full request body, but I guess it's sufficient for your use case :-)

**Comment by sirdarckcat** [comment]
I'll keep track of this feature request on #18 as part of the UI simplicification efforts.

**Comment by homakov** [comment]
can you elaborate about not full body? is it chopped at some point? Most requests I care about are under 10000 chars
