### ISSUE TITLE
no "tamper" element in dev tools

### ISSUE THREAD

**Issue by damnms** [google/tamperchrome#41]
i am using chromium, seems like this addon is incompatible?
after extracting the .zip and installing it, i have no "tamper" in the dev tools

**Comment by siwalikm** [comment]
Can confirm, didn't work for me as well. `Chrome Version 79.0.3945.130 (Official Build) (64-bit)`

**Comment by sirdarckcat** [comment]
Which zip?

**Comment by damnms** [comment]
https://github.com/google/tamperchrome/releases/download/1.3.3/1.3.3.zip

**Comment by sirdarckcat** [comment]
That's not the right bundle, only the subdirectory of extension and app are valid extension bundles.

It's easier if you install from here:
https://chrome.google.com/webstore/detail/tamper-chrome-extension/hifhgpdkfodlpnlmlnmhchnkepplebkb
