### ISSUE TITLE
can you add a frickin enable and turn off button ... because this f***kin messed up !

### ISSUE THREAD

**Issue by minanagehsalalma** [google/tamperchrome#46]
![image](https://user-images.githubusercontent.com/20546638/89244684-683a7c80-d607-11ea-8bcb-a638df15a33e.png)
it hanged like this and wouldn't fuckin turn off even if i disabled the extension 

i had to remove the app !

**Comment by sirdarckcat** [comment]
What made it hang? Sounds like a bug, but I'm not sure if there's enough information to reproduce this :-(
