### ISSUE TITLE
Tamper Chrome is not working

### ISSUE THREAD

**Issue by ivikash** [google/tamperchrome#6]
Hey, I was trying out Tamper Chrome, but I am not able to get it to work. It is always saying `"Could not find Tamper Chrome Application`

<img width="622" alt="screen shot 2017-04-26 at 1 26 19 pm" src="https://cloud.githubusercontent.com/assets/371007/25423955/2a39e894-2a84-11e7-9d5b-686fcbf7f2f5.png">

**Comment by halvardos** [comment]
I'm having the exact same problem on:
Chrome Version 57.0.2987.133 (64-bit)
OSX 10.11.6 (15G1217)

**Comment by jonthegiant** [comment]
This was my initial issue too, but if you read the second line...
'... extension requires the Taper Chrome packaged application...'

In reality Tamper Chrome is seemingly two parts: the extension and the packaged application.

Once you download and install both, it should work.

Perhaps the README could be updated to reflect the requirement?

**Comment by halvardos** [comment]
ah, actually i read it. But when I clicked the link and ended up on the chrome web store i though i was back to the plugin page. My bad. But could probably be even more explicit :)

**Comment by ivikash** [comment]
Thanks. Its done 👍
