### ISSUE TITLE
Modify post body

### ISSUE THREAD

**Issue by nitish24p** [google/tamperchrome#7]
When i block a request, is there a way for me to modify the post body and then forward it to the intended server.

**Comment by sirdarckcat** [comment]
hi

does "replay" do what you need? please give it a try and let me know.

https://github.com/google/tamperchrome#replay-requests-experimental

**Comment by sirdarckcat** [comment]
please @ me if this doesn't work for your use case.

thank you

**Comment by philly-vanilly** [comment]
Hi @sirdarckcat for me this does not work. I have selected "block/reroute requests" and "replay requests". So I see two types of requests now:
- blockRequest
- requestFinished

I cannot modify, only block the first one. And the second one (requestFinished) I can modify, but when I click on SEND, in the history I see that it sent the original and not modified body.

Please provide some additional information how to use this correctly. On https://github.com/google/tamperchrome#replay-requests-experimental it is not clear!
